# -*- coding: utf-8 -*-
"""Detector_Peatones_Updated_Model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UP-ryfZFj_txV2WuDJTZyVs2X9XLLWdD

# **Instalar Roboflow**
"""

!pip install roboflow ultralytics

"""## **Importar dataset desde Roboflow**"""

!pip install roboflow

from roboflow import Roboflow
rf = Roboflow(api_key="uSycsyYpzEntTgso0USM")
project = rf.workspace("erness-workspace").project("person-detect-1j2d0")
version = project.version(3)
dataset = version.download("yolov11")

"""## **Importar dataset desde Roboflow**"""

from ultralytics import YOLO
model = YOLO("yolo11s.pt")

"""## **Entrenamiento**"""

data_path="/content/Person-Detect-3/data.yaml"
model.train(
    data=data_path,
    epochs=100,
    imgsz=640,
    batch=250,
    device=0
)

"""## **Descargar resultados**"""

!zip -r runs.zip /content/runs
from google.colab import files
files.download("runs.zip")

"""## **Predicciones**"""

custom_model = YOLO("/content/runs/detect/train/weights/best.pt")
res = custom_model("/content/detector-peatones-2/test/images")
n = len(res)
for i in range(n):
  res[i].show()